--- 
abstract: Use Gnavi API From Perl
author: Copyright (c) 2007 Daisuke Maki <daisuke@endeworks.jp>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WebService-Gnavi
no_index: 
  directory: 
    - inc
    - t
requires: 
  Data::Page: 0
  LWP::UserAgent: 0
  URI: 0
  XML::LibXML: 0
version: 0.02
